Matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

compiler: gcc

before script: 
 - if [ "$(uname)" = "Linux" ]; then sudo apt-get update; sudo apt-get install check

script: make test
